DROP TABLE IF EXISTS user;
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nick TEXT UNIQUE NOT NULL,
  haslo TEXT NOT NULL
);

DROP TABLE IF EXISTS zadanie;
CREATE TABLE zadanie (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  zadanie TEXT NOT NULL,
  zrobione BOOLEAN NOT NULL DEFAULT FALSE,
  data_dodania DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS wiadomosc;
CREATE TABLE wiadomosc (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  wiadomosc TEXT NOT NULL,
  data_dodania DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS pytanie;
CREATE TABLE pytanie (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pytanie TEXT NOT NULL
);

DROP TABLE IF EXISTS odpowiedz;
CREATE TABLE odpowiedz (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pytanie_id INTEGER,
    odpowiedz TEXT NOT NULL,
    poprawna BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (pytanie_id) REFERENCES pytanie(id) ON DELETE CASCADE
);
